import {query} from '@/lib/db';
import {FolderKanban,BriefcaseBusiness,Inbox,ArrowUpLeft} from 'lucide-react';
import {PageHeader,QuickLink,StatusBadge} from '@/components/admin/AdminUI';
export const dynamic='force-dynamic';
export default async function Page(){
 const [[p],[pub],[s],[m],[u]] = await Promise.all(['SELECT count(*) c FROM projects','SELECT count(*) c FROM projects WHERE status=\'published\'','SELECT count(*) c FROM services','SELECT count(*) c FROM messages','SELECT count(*) c FROM messages WHERE status=\'unread\''].map(async sql=>(await query(sql)).rows));
 const stats=[['المشاريع',(p as any).c,FolderKanban],['منشور',(pub as any).c,ArrowUpLeft],['الخدمات',(s as any).c,BriefcaseBusiness],['الرسائل',(m as any).c,Inbox],['غير المقروء',(u as any).c,Inbox]];
 return <><PageHeader eyebrow="لوحة التحكم" title="أهلًا بك في ShoTech" description="من هنا تدير كل ما يظهر على الموقع: المحتوى، الخدمات، المشاريع، الرسائل وإعدادات الشركة."/><div className="admin-stats">{stats.map(([label,value,Icon]:any)=><div className="admin-stat" key={label}><span>{label}</span><strong>{value}</strong><Icon size={17}/></div>)}</div><section className="admin-card"><div className="admin-card-head"><div><h2>إدارة سريعة</h2><p>اختصارات لأهم المهام بدل البحث داخل الصفحات.</p></div></div><div className="admin-quick-grid"><QuickLink href="/admin/sections" title="إدارة محتوى الموقع" description="الأقسام، النصوص، الصور والأيقونات"/><QuickLink href="/admin/services" title="إدارة الخدمات" description="إضافة وتعديل خدمات الشركة"/><QuickLink href="/admin/projects" title="إدارة المشاريع" description="الصور، التفاصيل وحالة النشر"/><QuickLink href="/admin/messages" title="رسائل العملاء" description="متابعة طلبات التواصل"/></div></section><section className="admin-card"><div className="admin-card-head"><div><h2>حالة الموقع</h2><p>كل شيء جاهز للإدارة من مكان واحد.</p></div><StatusBadge tone="success">النظام يعمل</StatusBadge></div><div className="admin-notice">أي تعديل تحفظه هنا ينعكس على الموقع العام بعد تحديث البيانات. لا تحتاج لتعديل الكود.</div></section></>;
}
