import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, Check, Sparkles } from 'lucide-react';
import { getProjects, getServices, getSettings, getSections } from '@/lib/site';
import { getServiceIcon } from '@/lib/service-icons';
import RevealOnScroll from '@/components/RevealOnScroll';
import HomeContact from '@/components/HomeContact';
export const dynamic='force-dynamic';
const fallbackServices=[{id:'1',title:'تطوير المواقع',description:'مواقع سريعة، احترافية، ومتجاوبة مصممة حول هدف مشروعك.',icon:'Globe2',slug:'web-development'},{id:'2',title:'الأنظمة الإدارية',description:'أنظمة مخصصة لإدارة المبيعات، العملاء، المخزون والعمليات اليومية.',icon:'LayoutDashboard',slug:'business-systems'},{id:'3',title:'تطبيقات الموبايل',description:'تطبيقات Android وiOS بتجربة استخدام واضحة وأداء عملي.',icon:'Smartphone',slug:'mobile-apps'},{id:'4',title:'قواعد البيانات والربط',description:'بنية بيانات منظمة وربط آمن بين أجزاء النظام المختلفة.',icon:'Database',slug:'databases'},{id:'5',title:'حلول مخصصة',description:'نحوّل الفكرة أو المشكلة المتكررة إلى أداة رقمية مناسبة.',icon:'Sparkles',slug:'custom-solutions'},{id:'6',title:'تطوير وتحسين',description:'تطوير الأنظمة الموجودة وتحسين السرعة وتجربة المستخدم.',icon:'Code2',slug:'development'}];
const fallbackProjects=[{id:'1',title:'أنظمة أعمال مخصصة',category:'BUSINESS SYSTEM',excerpt:'حلول رقمية صُممت لتبسيط التشغيل والمتابعة اليومية.',slug:'business-systems'},{id:'2',title:'متاجر ومنصات رقمية',category:'WEB PLATFORM',excerpt:'تجارب ويب حديثة تساعد المشروع على الظهور والبيع بشكل أفضل.',slug:'web-platforms'},{id:'3',title:'تطبيقات موبايل',category:'MOBILE APP',excerpt:'تطبيقات عملية تربط العميل بالخدمة في خطوات واضحة.',slug:'mobile-apps'}];
export default async function Home(){
 const [settings,servicesData,projectsData,sections]=await Promise.all([getSettings(),getServices(),getProjects(true),getSections('home')]);
 const services=servicesData.length?servicesData.slice(0,6):fallbackServices;
 const projects=projectsData.length?projectsData.slice(0,3):fallbackProjects;
 const sectionMap:Record<string,any>=Object.fromEntries(sections.map((s:any)=>[s.type,s]));
 const about=settings.aboutBody||'نحن في ShoTech نعمل على تحويل الأفكار والاحتياجات اليومية إلى حلول رقمية بسيطة، سريعة، وقابلة للتوسع. لا نبيع منتجًا واحدًا للجميع؛ نبني ما يناسب طبيعة كل مشروع.';
 const hero=sectionMap.hero,servicesSection=sectionMap.services,aboutSection=sectionMap.about,projectsSection=sectionMap.projects;
 return <main>
 {hero&&<section className="hero container"><RevealOnScroll className="hero-copy"><h1>{hero.title||'نبني حلولًا رقمية'}<br/><span>{hero.subtitle||'تشتغل معاك.'}</span></h1><p className="hero-lead">{hero.body||'من موقع احترافي إلى نظام متكامل لإدارة شغلك، بنحوّل احتياجاتك إلى تجربة رقمية واضحة، سريعة، ومصممة حول طريقة عملك.'}</p><div className="hero-actions"><Link href="#contact" className="btn btn-primary">{hero.button_text||'ابدأ مشروعك'} <ArrowLeft size={18}/></Link><Link href="#projects" className="btn btn-outline">شوف أعمالنا</Link></div><div className="hero-note"><span><i/> حلول مخصصة</span><span><i/> تصميم وتجربة مستخدم</span><span><i/> دعم وتطوير مستمر</span></div></RevealOnScroll></section>}
 {servicesSection&&<section id="services" className="section section-soft"><div className="container"><RevealOnScroll className="section-head"><div><div className="eyebrow">خدماتنا</div><h2>{servicesSection.title||'كل اللي مشروعك محتاجه'}<br/>{servicesSection.subtitle||'في مكان واحد.'}</h2></div><p className="muted">{servicesSection.body||'بنختار التقنية على أساس احتياجك، مش العكس. والنتيجة حل واضح وسهل استخدامه وتطويره.'}</p></RevealOnScroll><div className="cards">{services.map((service:any,i:number)=>{const Icon=getServiceIcon(service.icon);const titleSize=Math.max(12,Math.min(20,430/Math.max(service.title.length,1)));return <RevealOnScroll key={service.id||i} delay={i*90}><article className="service-card"><div style={{display:'flex',alignItems:'center',gap:12,minWidth:0}}><div className="service-icon" style={{flex:'0 0 54px'}}><Icon size={24}/></div><h3 style={{margin:0,flex:1,minWidth:0,fontSize:`${titleSize}px`,lineHeight:1.25,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{service.title}</h3></div><p style={{marginTop:22}}>{service.description}</p><Link className="card-link" href={`/services/${service.slug}`}>اعرف أكتر <ArrowLeft size={15}/></Link></article></RevealOnScroll>})}</div></div></section>}
 {projectsSection&&<section id="projects" className="section"><div className="container"><RevealOnScroll className="section-head"><div><div className="eyebrow">أعمالنا</div><h2>{projectsSection.title||'مشاريع حقيقية.'}<br/>{projectsSection.subtitle||'نتائج عملية.'}</h2></div><Link href="/projects" className="btn btn-outline">{projectsSection.button_text||'كل الأعمال'} <ArrowLeft size={17}/></Link></RevealOnScroll><div className="projects">{projects.map((project:any,i:number)=>{let images:string[]=[];try{images=JSON.parse(project.images||'[]')}catch{}const cover=project.cover_image||images[0];return <RevealOnScroll key={project.id||i} delay={i*100}><Link href={`/projects/${project.slug}`} className="project-card"><div className="project-media">{cover?<Image src={cover} alt={project.title} width={700} height={450}/>:<div className="project-placeholder"><Sparkles size={34}/></div>}</div><div className="project-body"><div className="project-meta">{project.category||'DIGITAL PROJECT'}</div><h3>{project.title}</h3><p>{project.excerpt}</p></div></Link></RevealOnScroll>})}</div></div></section>}
 {aboutSection&&<section id="about" className="section about-section"><div className="container"><RevealOnScroll><div className="about-content"><h2>{aboutSection.title||'مش مجرد موقع. نبني لك نظام.'}</h2><p className="muted">{aboutSection.body||about}</p><div className="check-list"><div className="check"><span className="check-mark"><Check size={14}/></span><div><b>نفهم الشغل الأول</b><span>نبدأ من طريقة عملك والمشكلة اللي عايز تحلها.</span></div></div><div className="check"><span className="check-mark"><Check size={14}/></span><div><b>نبني بشكل عملي</b><span>واجهة سهلة، كود منظم، وبنية قابلة للتوسع.</span></div></div><div className="check"><span className="check-mark"><Check size={14}/></span><div><b>نكمل معاك</b><span>التطوير مش بيقف عند التسليم.</span></div></div></div><Link href={aboutSection.button_url||'/about'} className="btn btn-outline">{aboutSection.button_text||'اعرف ShoTech أكتر'} <ArrowLeft size={17}/></Link></div></RevealOnScroll></div></section>}
 <HomeContact settings={settings}/>
 </main>
}
