import { createClient } from '@libsql/client';
const url = process.env.TURSO_DATABASE_URL; const isVercel = process.env.VERCEL === '1';
if (!url && isVercel) throw new Error('TURSO_DATABASE_URL is required on Vercel. Add TURSO_DATABASE_URL and TURSO_AUTH_TOKEN in Project Settings → Environment Variables.');
export const db=createClient({url:url||'file:local.db',authToken:process.env.TURSO_AUTH_TOKEN});
const schema=[
`CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,excerpt TEXT,content TEXT,cover_image TEXT,images TEXT DEFAULT '[]',technologies TEXT DEFAULT '[]',category TEXT,demo_url TEXT,github_url TEXT,status TEXT DEFAULT 'draft',featured INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS services (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT,content TEXT DEFAULT '',slug TEXT,cover_image TEXT DEFAULT '',icon TEXT DEFAULT 'Code2',sort_order INTEGER DEFAULT 0,visible INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT,message TEXT NOT NULL,status TEXT DEFAULT 'unread',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS site_sections (id INTEGER PRIMARY KEY AUTOINCREMENT,page TEXT NOT NULL DEFAULT 'home',type TEXT NOT NULL DEFAULT 'custom',title TEXT DEFAULT '',subtitle TEXT DEFAULT '',body TEXT DEFAULT '',icon TEXT DEFAULT '',image TEXT DEFAULT '',button_text TEXT DEFAULT '',button_url TEXT DEFAULT '',data TEXT DEFAULT '{}',sort_order INTEGER DEFAULT 0,visible INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
`INSERT OR IGNORE INTO settings(key,value) VALUES ('companyName','ShoTech Solutions'),('tagline','حلول ذكية. أنظمة قوية.'),('email',''),('whatsapp',''),('facebook',''),('instagram',''),('linkedin',''),('github',''),('seoTitle','ShoTech Solutions'),('seoDescription','حلول رقمية ذكية وأنظمة قوية تساعد عملك على النمو.'),('aboutTitle','حلول ذكية. أنظمة قوية.'),('aboutBody','نبني منتجات رقمية عملية وأنظمة مخصصة تساعد الشركات على العمل بشكل أفضل، والتحرك بشكل أسرع، والنمو بثقة.'),('processTitle','طريقة شغل واضحة. ونتيجة أقوى.'),('processBody','نفهم، نصمم، نبني ونطلق حلولًا رقمية حول احتياجات كل مشروع.')`,
`INSERT OR IGNORE INTO site_sections(page,type,title,subtitle,body,sort_order,visible) VALUES ('home','hero','نحوّل أفكارك إلى أنظمة رقمية قوية.','ShoTech Solutions • حلول رقمية','نصمم ونبني مواقع حديثة، وأنظمة أعمال مخصصة، وتجارب رقمية تساعد المشاريع الطموحة على العمل بشكل أسرع وأوضح.',10,1),('home','services','تقنية مصممة حول شغلك.','خدماتنا','من أول الفكرة إلى نظام جاهز للعمل، نبني حلولًا واضحة لها هدف حقيقي.',20,1),('home','about','عن ShoTech','من نحن','نبني منتجات رقمية عملية وأنظمة مخصصة حول الاحتياجات الحقيقية للمشاريع الطموحة.',30,1),('home','why','ليه ShoTech؟','لماذا تختارنا','حلول مخصصة، تواصل واضح، بنية قابلة للتطوير، وطريقة شغل تركز على نتيجة حقيقية.',40,1),('home','process','طريقة شغلنا','خطوات التنفيذ','نفهم، نصمم، نبني ونطلق — طريقة بسيطة بنتيجة أقوى.',50,1),('home','projects','أنظمة معمولة عشان تشتغل.','أعمالنا','استكشف مجموعة من المشاريع التي بنيناها لحل مشاكل حقيقية في الأعمال.',60,1),('home','cta','خلينا نبني حاجة مفيدة','ابدأ مشروعك','احكيلنا أنت عايز تبني إيه، وإحنا نحدد معاك الحل الرقمي المناسب.',70,1),('about','about','حلول ذكية. أنظمة قوية.','','نبني منتجات رقمية عملية وأنظمة مخصصة تساعد الشركات على العمل بشكل أفضل، والتحرك بشكل أسرع، والنمو بثقة.',10,1),('process','process','طريقة شغل واضحة. ونتيجة أقوى.','','نفهم، نصمم، نبني ونطلق — وكل خطوة بتتدار حول أهداف مشروعك.',10,1)`
];
const migrations=[
`ALTER TABLE services ADD COLUMN content TEXT DEFAULT ''`,`ALTER TABLE services ADD COLUMN slug TEXT`,`ALTER TABLE services ADD COLUMN cover_image TEXT DEFAULT ''`,`ALTER TABLE services ADD COLUMN visible INTEGER DEFAULT 1`,
`ALTER TABLE services ADD COLUMN title_en TEXT DEFAULT ''`,`ALTER TABLE services ADD COLUMN description_en TEXT DEFAULT ''`,`ALTER TABLE services ADD COLUMN content_en TEXT DEFAULT ''`,
`ALTER TABLE projects ADD COLUMN title_en TEXT DEFAULT ''`,`ALTER TABLE projects ADD COLUMN excerpt_en TEXT DEFAULT ''`,`ALTER TABLE projects ADD COLUMN content_en TEXT DEFAULT ''`,`ALTER TABLE projects ADD COLUMN category_en TEXT DEFAULT ''`,
`ALTER TABLE site_sections ADD COLUMN title_en TEXT DEFAULT ''`,`ALTER TABLE site_sections ADD COLUMN subtitle_en TEXT DEFAULT ''`,`ALTER TABLE site_sections ADD COLUMN body_en TEXT DEFAULT ''`,`ALTER TABLE site_sections ADD COLUMN button_text_en TEXT DEFAULT ''`
];
let initPromise:Promise<void>|null=null;
export function ensureDatabase(){if(!initPromise){initPromise=(async()=>{for(const sql of schema)await db.execute(sql);for(const sql of migrations){try{await db.execute(sql)}catch{}}await db.execute(`UPDATE services SET slug=lower(replace(replace(trim(title),' ','-'),'--','-')) WHERE slug IS NULL OR slug=''`);
const settingTranslations:[string,string,string][]=[['tagline','Smart Solutions. Powerful Systems.','حلول ذكية. أنظمة قوية.'],['seoDescription','Smart digital solutions and powerful systems.','حلول رقمية ذكية وأنظمة قوية تساعد عملك على النمو.'],['aboutTitle','Smart solutions. Powerful systems.','حلول ذكية. أنظمة قوية.'],['aboutBody','ShoTech Solutions builds practical digital products that help businesses operate better, move faster and grow with confidence.','نبني منتجات رقمية عملية وأنظمة مخصصة تساعد الشركات على العمل بشكل أفضل، والتحرك بشكل أسرع، والنمو بثقة.'],['processTitle','A clear process. A stronger result.','طريقة شغل واضحة. ونتيجة أقوى.'],['processBody','We discover, design, build and launch digital systems around the real needs of each business.','نفهم، نصمم، نبني ونطلق حلولًا رقمية حول احتياجات كل مشروع.']];
for(const [key,from,to] of settingTranslations)await db.execute('UPDATE settings SET value=? WHERE key=? AND value=?',[to,key,from]);
const englishSettings:[string,string][]=[['companyName_en','ShoTech Solutions'],['tagline_en','Smart solutions. Powerful systems.'],['seoTitle_en','ShoTech Solutions | Digital solutions that make a difference'],['seoDescription_en','Smart digital solutions and powerful systems that help businesses grow.'],['aboutTitle_en','Smart solutions. Powerful systems.'],['aboutBody_en','We build practical digital products and custom systems that help businesses operate better, move faster and grow with confidence.'],['processTitle_en','A clear process. A stronger result.'],['processBody_en','We discover, design, build and launch digital solutions around the real needs of each business.']];
for(const [key,value] of englishSettings)await db.execute('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)',[key,value]);
const sectionTranslations:[string,string,string,string,string,string][]=[
['home','hero','نحوّل أفكارك إلى أنظمة رقمية قوية.','We turn ideas into powerful digital systems.','ShoTech Solutions • حلول رقمية','ShoTech Solutions • Digital solutions'],
['home','services','تقنية مصممة حول شغلك.','Technology designed around your business.','خدماتنا','Our services'],
['home','about','عن ShoTech','About ShoTech','من نحن','About us'],
['home','why','ليه ShoTech؟','Why ShoTech?','لماذا تختارنا','Why choose us'],
['home','process','طريقة شغلنا','How we work','خطوات التنفيذ','Our process'],
['home','projects','أنظمة معمولة عشان تشتغل.','Systems built to perform.','أعمالنا','Our work'],
['home','cta','خلينا نبني حاجة مفيدة','Let’s build something useful','ابدأ مشروعك','Start your project'],
['about','about','حلول ذكية. أنظمة قوية.','Smart solutions. Powerful systems.','',''],
['process','process','طريقة شغل واضحة. ونتيجة أقوى.','A clear process. A stronger result.','','']];
for(const [page,type,arTitle,enTitle,arSub,enSub] of sectionTranslations)await db.execute('UPDATE site_sections SET title_en=?,subtitle_en=? WHERE page=? AND type=? AND (title_en IS NULL OR title_en="")',[enTitle,enSub,page,type]);
const bodyTranslations:[string,string,string,string][]=[['home','hero','نصمم ونبني مواقع حديثة، وأنظمة أعمال مخصصة، وتجارب رقمية تساعد المشاريع الطموحة على العمل بشكل أسرع وأوضح.','We design and build modern websites, custom business systems and digital experiences that help ambitious businesses move faster and work more clearly.'],['home','services','من أول الفكرة إلى نظام جاهز للعمل، نبني حلولًا واضحة لها هدف حقيقي.','From the first idea to a production-ready system, we build focused solutions with a clear purpose.'],['home','about','نبني منتجات رقمية عملية وأنظمة مخصصة حول الاحتياجات الحقيقية للمشاريع الطموحة.','We build practical digital products and custom systems around the real needs of ambitious businesses.'],['home','why','حلول مخصصة، تواصل واضح، بنية قابلة للتطوير، وطريقة شغل تركز على نتيجة حقيقية.','Custom solutions, clear communication, scalable architecture and a process focused on real results.'],['home','process','نفهم، نصمم، نبني ونطلق — طريقة بسيطة بنتيجة أقوى.','Discover, design, build and launch — a simple process with a stronger result.'],['home','projects','استكشف مجموعة من المشاريع التي بنيناها لحل مشاكل حقيقية في الأعمال.','Explore selected projects built to solve real business problems.'],['home','cta','احكيلنا أنت عايز تبني إيه، وإحنا نحدد معاك الحل الرقمي المناسب.','Tell us what you want to build and we will shape the right digital solution.'],['about','about','نبني منتجات رقمية عملية وأنظمة مخصصة تساعد الشركات على العمل بشكل أفضل، والتحرك بشكل أسرع، والنمو بثقة.','We build practical digital products and custom systems that help businesses operate better, move faster and grow with confidence.'],['process','process','نفهم، نصمم، نبني ونطلق — وكل خطوة بتتدار حول أهداف مشروعك.','We discover, design, build and launch — with every step managed around your business goals.']];
for(const [page,type,arBody,enBody] of bodyTranslations)await db.execute('UPDATE site_sections SET body_en=? WHERE page=? AND type=? AND (body_en IS NULL OR body_en="")',[enBody,page,type]);
const coreByPage:[string,string[]][]=[['home',['hero','services','about','why','process','projects','cta']],['about',['about']],['why',['why']],['process',['process']]];
for(const [page,types] of coreByPage){for(const type of types){await db.execute(`DELETE FROM site_sections WHERE page=? AND type=? AND id NOT IN (SELECT MIN(id) FROM site_sections WHERE page=? AND type=?)`,[page,type,page,type]);}}
try{await db.execute(`CREATE UNIQUE INDEX IF NOT EXISTS idx_site_sections_core_unique ON site_sections(page,type) WHERE type IN ('hero','services','about','why','process','projects','cta')`)}catch{}
})().catch(e=>{initPromise=null;throw e})}return initPromise}
export async function query(sql:string,args:any[]=[]){await ensureDatabase();return db.execute({sql,args})}
