'use client';
import {useState} from 'react';
import {Code2,ShoppingCart,Building2,LayoutDashboard,MonitorSmartphone,Workflow,Sparkles,Globe2,Database,Smartphone,Palette,ShieldCheck,Rocket,Settings,Layers3,Server,Cloud,Zap,Users,MessageCircle,Mail,Phone,Search,ChartNoAxesCombined,Heart,Star,Lightbulb,Headphones,LockKeyhole,PenTool,FileText,Image as ImageIcon,Briefcase,Bot,Boxes, type LucideIcon} from 'lucide-react';
const ICONS:Record<string,LucideIcon>={Code2,ShoppingCart,Building2,LayoutDashboard,MonitorSmartphone,Workflow,Sparkles,Globe2,Database,Smartphone,Palette,ShieldCheck,Rocket,Settings,Layers3,Server,Cloud,Zap,Users,MessageCircle,Mail,Phone,Search,ChartNoAxesCombined,Heart,Star,Lightbulb,Headphones,LockKeyhole,PenTool,FileText,ImageIcon,Briefcase,Bot,Boxes};
const labels:Record<string,string>={Code2:'برمجة',ShoppingCart:'متجر إلكتروني',Building2:'شركات وأعمال',LayoutDashboard:'لوحات تحكم',MonitorSmartphone:'ويب وتطبيق',Workflow:'أتمتة',Sparkles:'حلول مبتكرة',Globe2:'مواقع',Database:'قواعد بيانات',Smartphone:'تطبيقات',Palette:'تصميم',ShieldCheck:'أمان',Rocket:'نمو وإطلاق',Settings:'إعدادات',Layers3:'أنظمة متكاملة',Server:'سيرفرات',Cloud:'سحابة',Zap:'سرعة وأداء',Users:'مستخدمون',MessageCircle:'تواصل',Mail:'بريد',Phone:'هاتف',Search:'بحث',ChartNoAxesCombined:'تحليلات',Heart:'اهتمام',Star:'مميز',Lightbulb:'أفكار',Headphones:'دعم',LockKeyhole:'حماية',PenTool:'أدوات',FileText:'محتوى',ImageIcon:'صور',Briefcase:'أعمال',Bot:'ذكاء اصطناعي',Boxes:'حلول متعددة'};
export default function IconPicker({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const [open,setOpen]=useState(false); const Icon=ICONS[value]||Sparkles;
 return <div className="icon-picker"><button type="button" className="icon-picker-trigger" onClick={()=>setOpen(!open)}><span className="icon-picker-preview"><Icon size={20}/></span><span><strong>{labels[value]||value||'اختر أيقونة'}</strong><small>{value||'لم يتم الاختيار'}</small></span><span className="icon-picker-chevron">⌄</span></button>{open&&<><button className="icon-picker-backdrop" aria-label="إغلاق" onClick={()=>setOpen(false)}/><div className="icon-picker-menu">{Object.entries(ICONS).map(([name,IconComp])=><button type="button" className={value===name?'selected':''} key={name} onClick={()=>{onChange(name);setOpen(false)}}><IconComp size={19}/><span>{labels[name]}</span></button>)}</div></>}</div>
}
export {ICONS};
