'use client';
import{useEffect,useState}from'react';
import{Pencil,Trash2,Eye,EyeOff,ImagePlus,Upload,ArrowUp,ArrowDown}from'lucide-react';
import IconPicker from'@/components/admin/IconPicker';
import{PageHeader,SectionCard,Field,SaveBar,StatusBadge}from'@/components/admin/AdminUI';
const blank:any={title:'',title_en:'',slug:'',description:'',description_en:'',content:'',content_en:'',icon:'Code2',cover_image:'',sort_order:0,visible:true};
export default function Page(){
 const[items,setItems]=useState<any[]>([]),[f,setF]=useState<any>({...blank}),[id,setId]=useState<number|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const load=()=>fetch('/api/services',{cache:'no-store'}).then(r=>r.json()).then(d=>setItems(Array.isArray(d)?d:[]));useEffect(()=>{load()},[]);
 const set=(k:string,v:any)=>setF((a:any)=>({...a,[k]:v}));
 async function upload(file:File){setUploading(true);setError('');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر رفع الصورة');set('cover_image',d.url||d.urls?.[0]||'')}catch(e:any){setError(e.message)}finally{setUploading(false)}}
 async function save(e:any){e.preventDefault();setError('');setSaving(true);try{const r=await fetch(id?`/api/services/${id}`:'/api/services',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok){setError(d.error||'تعذر الحفظ');return}cancel();await load()}finally{setSaving(false)}}
 async function del(i:number){if(!confirm('حذف هذه الخدمة نهائيًا؟'))return;const r=await fetch(`/api/services/${i}`,{method:'DELETE'});if(!r.ok)setError('تعذر حذف الخدمة.');await load()}
 async function toggle(s:any){const r=await fetch(`/api/services/${s.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,visible:!s.visible})});if(!r.ok)setError('تعذر تغيير حالة الخدمة.');await load()}
 function edit(x:any){setId(x.id);setF({...blank,...x,visible:!!x.visible});setError('');window.scrollTo({top:0,behavior:'smooth'})}function cancel(){setId(null);setF({...blank});setError('')}
 return <><PageHeader eyebrow="الخدمات" title="خدمات ShoTech" description="إدارة الخدمات بالكامل من الهاتف: المحتوى، الصورة، الأيقونة، الترتيب والظهور." action="إضافة خدمة" actionHref="#service-form"/>
 <form id="service-form" onSubmit={save}><SectionCard title={id?'تعديل الخدمة':'إضافة خدمة'}><div className="admin-grid"><Field label="اسم الخدمة — عربي" required><input value={f.title} onChange={e=>set('title',e.target.value)} required/></Field><Field label="Service name — English"><input value={f.title_en||''} onChange={e=>set('title_en',e.target.value)}/></Field></div><div className="admin-grid"><Field label="الرابط المختصر"><input value={f.slug} onChange={e=>set('slug',e.target.value)} placeholder="web-development"/></Field><Field label="الترتيب"><input type="number" min="0" value={f.sort_order} onChange={e=>set('sort_order',Math.max(0,+e.target.value||0))}/></Field></div>
 <Field label="صورة الغلاف"><div className="admin-upload-row"><label className="admin-secondary"><Upload size={16}/>{uploading?'جاري الرفع...':'رفع صورة من الهاتف'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);e.currentTarget.value=''}}/></label><button type="button" className="admin-secondary" onClick={()=>set('cover_image','')}><ImagePlus size={16}/> إزالة الصورة</button></div>{f.cover_image&&<img className="admin-media-preview" src={f.cover_image} alt=""/>}</Field>
 <div className="admin-grid"><Field label="الوصف — عربي"><textarea value={f.description} onChange={e=>set('description',e.target.value)}/></Field><Field label="Description — English"><textarea value={f.description_en||''} onChange={e=>set('description_en',e.target.value)}/></Field></div><div className="admin-grid"><Field label="المحتوى — عربي"><textarea style={{minHeight:180}} value={f.content} onChange={e=>set('content',e.target.value)}/></Field><Field label="Content — English"><textarea style={{minHeight:180}} value={f.content_en||''} onChange={e=>set('content_en',e.target.value)}/></Field></div><div className="admin-grid"><Field label="الأيقونة"><IconPicker value={f.icon} onChange={v=>set('icon',v)}/></Field><div/></div><label className="admin-check"><input type="checkbox" checked={!!f.visible} onChange={e=>set('visible',e.target.checked)}/> إظهار الخدمة على الموقع</label>{error&&<div className="admin-error">{error}</div>}<SaveBar editing={!!id} onCancel={cancel} saving={saving||uploading}/></SectionCard></form>
 <SectionCard title="الخدمات الحالية" description={`${items.length} خدمة مسجلة.`}>{items.length?<div className="admin-list">{items.map((s,i)=><article className="admin-item" key={s.id}><div className="admin-item-main">{s.cover_image?<img className="admin-service-thumb" src={s.cover_image} alt=""/>:<div className="admin-item-icon">{s.icon}</div>}<div><h3>{s.title}</h3><p>/{s.slug} · ترتيب {s.sort_order||0}</p></div></div><div className="admin-actions"><StatusBadge tone={s.visible?'success':'neutral'}>{s.visible?'ظاهرة':'مخفية'}</StatusBadge><button type="button" className="admin-action" onClick={()=>edit(s)}><Pencil size={14}/> تعديل</button><button type="button" className="admin-action" onClick={()=>toggle(s)}>{s.visible?<EyeOff size={14}/>:<Eye size={14}/>} {s.visible?'إخفاء':'إظهار'}</button><button type="button" className="admin-action danger" onClick={()=>del(s.id)}><Trash2 size={14}/> حذف</button></div></article>)}</div>:<div className="admin-empty"><h3>لا توجد خدمات</h3><p>أضف أول خدمة للشركة.</p></div>}</SectionCard></>}
